apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: y4y95j6jh-go
  janus-idp.io/tekton: y4y95j6jh-go
  backstage.io/kubernetes-id: y4y95j6jh-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: y4y95j6jh-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
